DROP TABLE person;
DROP TABLE firm;
DROP TABLE WORKER;
CREATE TABLE person
(
	person_Id INT NOT NULL IDENTITY PRIMARY KEY,
	Name VARCHAR(255) NOT NULL,
	Second_name VARCHAR(255)NOT NULL,
	Birth_date datetime,
	Telephone VARCHAR(15),
	Adress VARCHAR(255)
);
CREATE TABLE firm
(
	firm_Id INT NOT NULL IDENTITY PRIMARY KEY,
	Name VARCHAR(255) NOT NULL,
	Adress VARCHAR(255)
);
CREATE TABLE WORKER
(
	firm_Id INT NOT NULL PRIMARY KEY,
	person_Id INT NOT NULL PRIMARY KEY,
)
;